name: Python Code Quality Checks (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-checks:
    name: Run Python Quality Checks
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'  # Match your Python version

    - name: Cache Python dependencies
      uses: actions/cache@v4
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'requirements_dev.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install linting tools
      run: pip install -r requirements_dev.txt

    - name: Run Black formatting check
      run: black --check wallpaper_py

    - name: Run Mypy type checking
      run: mypy wallpaper_py

    - name: Run Pylint analysis
      run: pylint wallpaper_py
